export const SHOW_SIDEBAR = "SHOW_SIDEBAR";

export const SHOW_MODAL = "SHOW_MODAL";

export const OPEN_ORDER_FORM = "OPEN_ORDER_FORM";

export const FROM_WHERE_SELECT = "FROM_WHERE_SELECT";
export const WHERE_SELECT = "WHERE_SELECT";

export const CHANGE_VALUE_INPUT = "CHANGE_VALUE_INPUT";

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_ERROR = "GET_REQUEST_ERROR";

export const POST_REQUEST = "POST_REQUEST";
export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS";
export const POST_REQUEST_ERROR = "POST_REQUEST_ERROR";

export const GALLERY_PHOTO = 'GALLERY_PHOTO';
