export const SHOW_SIDEBAR = "SHOW_SIDEBAR";

export const SHOW_MODAL = "SHOW_MODAL";

export const OPEN_ORDER_FORM = "OPEN_ORDER_FORM";

export const FROM_WHERE_SELECT = "FROM_WHERE_SELECT";
export const WHERE_SELECT = "WHERE_SELECT";

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_ERROR = "GET_REQUEST_ERROR";