export const SHOW_SIDEBAR = "SHOW_SIDEBAR";

export const SHOW_MODAL = "SHOW_MODAL";

export const OPEN_ORDER_FORM = "OPEN_ORDER_FORM";

export const FROM_WHERE_SELECT = "FROM_WHERE_SELECT";
export const WHERE_SELECT = "WHERE_SELECT";